src/main/java/com/ghebits/dahlakbookshop/oodm/catalog/model/CategoriesBean.java
package com.ghebits.dahlakbookshop.oodm.catalog.model;

import com.ghebits.dahlakbookshop.oodm.catalog.entities.CategoryDescription;

import java.util.List;
import java.util.Map;

/**
 * Created by tw on 01.01.15.
 */
public class CategoriesBean {

    private List<CategoryDescription> categories;

    private Map<CategoryDescription,Integer> category2level;

    public List<CategoryDescription> getCategories() {
        return categories;
    }

    public void setCategories(List<CategoryDescription> categories) {
        this.categories = categories;
    }

    public Map<CategoryDescription, Integer> getCategory2level() {
        return category2level;
    }

    public void setCategory2level(Map<CategoryDescription, Integer> category2level) {
        this.category2level = category2level;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CategoriesBean)) return false;

        CategoriesBean that = (CategoriesBean) o;

        if (categories != null ? !categories.equals(that.categories) : that.categories != null) return false;
        if (category2level != null ? !category2level.equals(that.category2level) : that.category2level != null)
            return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = categories != null ? categories.hashCode() : 0;
        result = 31 * result + (category2level != null ? category2level.hashCode() : 0);
        return result;
    }
}

src/main/java/com/ghebits/dahlakbookshop/oodm/customer/entities/AddressBook.java
package com.ghebits.dahlakbookshop.oodm.customer.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/*
address_book_id	int(11)	NO	PRI		auto_increment
customers_id	int(11)	NO	MUL		
entry_gender	char(1)	YES			
entry_company	varchar(255)	YES			
entry_firstname	varchar(255)	NO			
entry_lastname	varchar(255)	NO			
entry_street_address	varchar(255)	NO			
entry_suburb	varchar(255)	YES			
entry_postcode	varchar(255)	NO			
entry_city	varchar(255)	NO			
entry_state	varchar(255)	YES			
entry_country_id	int(11)	NO		0	
entry_zone_id	int(11)	NO		0	
 */
@Entity
@Table(name="address_book")
public class AddressBook {

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name="address_book_id", columnDefinition = "INT(11)")
	private Long id;
	
	@ManyToOne
	@JoinColumn(name="customers_id")
	private Customer customer;
	
	@Column(name="entry_gender", columnDefinition = "char(1)")
	private String gender;
	
	@Column(name="entry_company")
	private String company;
	
	@Column(name="entry_firstname")
	private String firstname;
	
	@Column(name="entry_lastname")
	private String lastname;
	
	@Column(name="entry_street_address")
	private String streetAddress;
	
	@Column(name="entry_suburb")
	private String suburb;
	
	@Column(name="entry_postcode")
	private String postcode;
	
	@Column(name="entry_city")
	private String city;
	
	@Column(name="entry_state")
	private String state;
	
	@ManyToOne
	@JoinColumn(name="entry_country_id")
	private Country country;
	
	@Column(name="entry_zone_id", columnDefinition = "INT(11)")
	private long zoneId=0;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Customer getCustomer() {
		return customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getCompany() {
		return company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getFirstname() {
		return firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getStreetAddress() {
		return streetAddress;
	}

	public void setStreetAddress(String streetAddress) {
		this.streetAddress = streetAddress;
	}

	public String getSuburb() {
		return suburb;
	}

	public void setSuburb(String suburb) {
		this.suburb = suburb;
	}

	public String getPostcode() {
		return postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Country getCountry() {
		return country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}
	
	public long getZoneId() {
		return zoneId;
	}

	public void setZoneId(long zoneId) {
		this.zoneId = zoneId;
	}

	@Override
	public String toString() {
		return "AddressBook [id=" + id + ", customer=" + customer + ", gender="
				+ gender + ", company=" + company + ", firstname=" + firstname
				+ ", lastname=" + lastname + ", streetAddress=" + streetAddress
				+ ", suburb=" + suburb + ", postcode=" + postcode + ", city="
				+ city + ", state=" + state + ", country=" + country
				+ ", zoneId=" + zoneId + "]";
	}
	
	@Transient
	public String getFormattedAddress(){
		return firstname+" "+lastname+"<br/>"+streetAddress+"<br/>"+postcode+" "+city+"<br/>"+country.getName();
	}
	
	@Transient
	public boolean isPrimaryAddress(){
		return customer.getDefaultAddress().getId()==this.id;
	}
}

src/main/java/com/ghebits/dahlakbookshop/backend/catalog/ManufacturerController.java
package com.ghebits.dahlakbookshop.backend.catalog;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import com.ghebits.dahlakbookshop.backend.AdminMenuCategory;
import com.ghebits.dahlakbookshop.oodm.catalog.entities.Manufacturer;
import com.ghebits.dahlakbookshop.oodm.catalog.service.ManufacturerService;
import com.ghebits.dahlakbookshop.oodm.catalog.service.ProductService;

import javax.inject.Inject;
import java.util.List;

/**
 * Created by tw on 30.01.15.
 */
@Controller
public class ManufacturerController {

    @Inject
    private ManufacturerService manufacturerService;

    @Inject
    private ProductService productService;

    @RequestMapping(value = "/admin/manufacturers", method = RequestMethod.GET)
    public String manufacturers(Model model){
        int menuCategory = AdminMenuCategory.CATALOG.ordinal();
        model.addAttribute("menuCategory",menuCategory);
        List<Manufacturer> manufacturers = manufacturerService.getAllManufacturers();
        model.addAttribute("manufacturers",manufacturers);
        int productsOfThisManufacturer = 0;
        Manufacturer thisManufacturer = null;
        if(manufacturers.size()>0){
            thisManufacturer = manufacturers.iterator().next();
            productsOfThisManufacturer = productService.countProductsOfThisManufacturer(thisManufacturer);
        }
        model.addAttribute("thisManufacturer",thisManufacturer);
        model.addAttribute("productsOfThisManufacturer",productsOfThisManufacturer);
        return "admin/catalog/manufacturers";
    }

    @RequestMapping(value = "/admin/manufacturers/{manufacturerId}", method = RequestMethod.GET)
    public String manufacturersId(
            @PathVariable long manufacturerId , Model model){
        int menuCategory = AdminMenuCategory.CATALOG.ordinal();
        model.addAttribute("menuCategory",menuCategory);
        List<Manufacturer> manufacturers = manufacturerService.getAllManufacturers();
        model.addAttribute("manufacturers",manufacturers);
        int productsOfThisManufacturer = 0;
        Manufacturer thisManufacturer = null;
        if(manufacturers.size()>0){
            thisManufacturer = manufacturerService.getManufacturerById(manufacturerId);
            productsOfThisManufacturer = productService.countProductsOfThisManufacturer(thisManufacturer);
        }
        model.addAttribute("thisManufacturer",thisManufacturer);
        model.addAttribute("productsOfThisManufacturer",productsOfThisManufacturer);
        return "admin/catalog/manufacturers";
    }
}

src/main/java/com/ghebits/dahlakbookshop/backend/catalog/SpecialController.java
package com.ghebits.dahlakbookshop.backend.catalog;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import com.ghebits.dahlakbookshop.backend.AdminMenuCategory;
import com.ghebits.dahlakbookshop.oodm.catalog.entities.*;
import com.ghebits.dahlakbookshop.oodm.catalog.model.*;
import com.ghebits.dahlakbookshop.oodm.catalog.service.LanguageService;
import com.ghebits.dahlakbookshop.oodm.catalog.service.SpecialService;

import javax.inject.Inject;
import java.util.Date;
import java.util.List;

/**
 * Created by tw on 31.12.14.
 */
@Controller
public class SpecialController {

    @Inject
    private LanguageService languageService;

    @Inject
    private SpecialService specialService;

    @RequestMapping(value = "/admin/specials", method = RequestMethod.GET)
    public String specials(Model model){
        int menuCategory = AdminMenuCategory.CATALOG.ordinal();
        model.addAttribute("menuCategory",menuCategory);
        Language language = languageService.findLanguageByCode("en");
        List<SpecialProduct> specials = specialService.getSpecialProducts(language);
        model.addAttribute("specials",specials);
        SpecialProduct thisSpecial = null;
        if(specials.size()>0){
            thisSpecial = specials.iterator().next();
        }
        model.addAttribute("thisSpecial",thisSpecial);
        return "admin/catalog/specials";
    }

    @RequestMapping(value = "/admin/specials/{productId}", method = RequestMethod.GET)
    public String specialsId(@PathVariable long productId,Model model){
        int menuCategory = AdminMenuCategory.CATALOG.ordinal();
        model.addAttribute("menuCategory",menuCategory);
        Language language = languageService.findLanguageByCode("en");
        List<SpecialProduct> specials = specialService.getSpecialProducts(language);
        model.addAttribute("specials",specials);
        SpecialProduct thisSpecial = null;
        if(specials.size()>0){
            thisSpecial = specialService.findSpecialProductById(productId, language);
        }
        model.addAttribute("thisSpecial",thisSpecial);
        return "admin/catalog/specials";
    }

    @RequestMapping(value = "/admin/specials/setInactive/{productId}", method = RequestMethod.GET)
    public String specialSetInactive(@PathVariable long productId,Model model){
        int menuCategory = AdminMenuCategory.CATALOG.ordinal();
        model.addAttribute("menuCategory",menuCategory);
        Language language = languageService.findLanguageByCode("en");
        SpecialProduct thisSpecial = specialService.findSpecialProductById(productId, language);
        Special special=thisSpecial.getSpecial();
        special.setStatus(false);
        special.setStatusChanged(new Date());
        specialService.updateSpecial(special);
        thisSpecial = specialService.findSpecialProductById(productId,language);
        model.addAttribute("thisSpecial",thisSpecial);
        List<SpecialProduct> specials = specialService.getSpecialProducts(language);
        model.addAttribute("specials",specials);
        return "admin/catalog/specials";
    }

    @RequestMapping(value = "/admin/specials/setActive/{productId}", method = RequestMethod.GET)
    public String specialSetActive(@PathVariable long productId,Model model){
        int menuCategory = AdminMenuCategory.CATALOG.ordinal();
        model.addAttribute("menuCategory",menuCategory);
        Language language = languageService.findLanguageByCode("en");
        SpecialProduct thisSpecial = specialService.findSpecialProductById(productId,language);
        Special special=thisSpecial.getSpecial();
        special.setStatus(true);
        special.setStatusChanged(new Date());
        specialService.updateSpecial(special);
        thisSpecial = specialService.findSpecialProductById(productId,language);
        model.addAttribute("thisSpecial",thisSpecial);
        List<SpecialProduct> specials = specialService.getSpecialProducts(language);
        model.addAttribute("specials",specials);
        return "admin/catalog/specials";
    }
}

src/main/java/com/ghebits/dahlakbookshop/frontend/CreateAccountController.java
package com.ghebits.dahlakbookshop.frontend;

import java.util.List;

import javax.inject.Inject;
import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.validation.FieldError;
import org.springframework.validation.ObjectError;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.SessionAttributes;
import com.ghebits.dahlakbookshop.oodm.customer.service.CountryService;
import com.ghebits.dahlakbookshop.oodm.customer.CustomerService;
import com.ghebits.dahlakbookshop.oodm.customer.entities.Country;
import com.ghebits.dahlakbookshop.oodm.customer.model.CreateNewCustomerFormBean;

@Controller
@SessionAttributes({"transientBasket"})
public class CreateAccountController extends AbstractController {

	private static final Logger logger = LoggerFactory.getLogger(CreateAccountController.class);
	
	@Inject
	private CustomerService customerService;

    @Inject
    private CountryService countryService;
	
	@RequestMapping(value = "/createAccount", method = RequestMethod.GET)
	public String createNewCustomerForm(Model model){
		super.getDefaultBoxContent(model);
		CreateNewCustomerFormBean createNewCustomerFormBean = new CreateNewCustomerFormBean();
		model.addAttribute("createNewCustomerFormBean",createNewCustomerFormBean);
		List<Country> allCountriesOrderByName = countryService.findAllCountriesOrderByName();
		model.addAttribute("allCountriesOrderByName",allCountriesOrderByName);
		return "createAccount";
	}
	
	@RequestMapping(value = "/createAccount", method = RequestMethod.POST)
	public String createNewCustomer(
			@Valid CreateNewCustomerFormBean createNewCustomerFormBean,
			BindingResult result, Model model){
		super.getDefaultBoxContent(model);
		if(customerService.findCustomerByEmail(createNewCustomerFormBean.getEmailAddress())!=null){
			result.addError(new FieldError("createNewCustomerFormBean","emailAddress", "is already in use, choose another one"));
		}
		if(!createNewCustomerFormBean.passwordsMatch()){
			result.addError(new FieldError("createNewCustomerFormBean","password", "passwords doesn't match"));
			result.addError(new FieldError("createNewCustomerFormBean","confirmation","passwords doesn't match"));
		}
		if(result.hasErrors()){
			List<Country> allCountriesOrderByName = countryService.findAllCountriesOrderByName();
			model.addAttribute("allCountriesOrderByName",allCountriesOrderByName);
			for(ObjectError e :result.getAllErrors()){
				logger.info(e.toString());
			}
			return "createAccount";
		} else {
			customerService.createNewCustomer(createNewCustomerFormBean);
			//login Customer
			UserDetails userDetails = customerService.loadUserByUsername(createNewCustomerFormBean.getEmailAddress());
			Authentication auth = new UsernamePasswordAuthenticationToken (userDetails.getUsername (),userDetails.getPassword (),userDetails.getAuthorities ());
			SecurityContextHolder.getContext().setAuthentication(auth);
			return "createdAccount";
		}
	}
}

src/main/java/com/ghebits/dahlakbookshop/frontend/LoginController.java
package com.ghebits.dahlakbookshop.frontend;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.SessionAttributes;

@Controller
@SessionAttributes({"transientBasket"})
public class LoginController extends AbstractController {

	private static final Logger logger = LoggerFactory.getLogger(LoginController.class);
	
	@RequestMapping(value = "/login", method = RequestMethod.GET)
	 public String showLoginForm(Model model){
		super.getDefaultBoxContent(model);
		return "login";
	}

	@RequestMapping(value = "/admin/login", method = RequestMethod.GET)
	public String showAdminLoginForm(Model model){
		return "admin/login";
	}
}

src/main/webapp/WEB-INF/jsp/account.jsp
<%@ include file="/WEB-INF/layout/taglibs.jsp"%>
<h1>My Account Information</h1>


<div class="contentContainer">
  <h2>My Account</h2>

  <div class="contentText">
    <ul class="accountLinkList">
      <li><span class="ui-icon ui-icon-person accountLinkListEntry"></span><a href='<c:url value="/accountEdit"/>'>View or change my account information.</a></li>
      <li><span class="ui-icon ui-icon-home accountLinkListEntry"></span><a href='<c:url value="/addressBook"/>'>View or change entries in my address book.</a></li>
      <li><span class="ui-icon ui-icon-key accountLinkListEntry"></span><a href='<c:url value="/accountPassword"/>'>Change my account password.</a></li>
    </ul>
  </div>

  <h2>My Orders</h2>

  <div class="contentText">
    <ul class="accountLinkList">
      <li><span class="ui-icon ui-icon-cart accountLinkListEntry"></span><a href='<c:url value="/accountHistory"/>'>View the orders I have made.</a></li>
    </ul>
  </div>

  <h2>E-Mail Notifications</h2>

  <div class="contentText">
    <ul class="accountLinkList">
      <li><span class="ui-icon ui-icon-mail-closed accountLinkListEntry"></span><a href='<c:url value="/accountNewsletter"/>'>Subscribe or unsubscribe from newsletters.</a></li>
      <li><span class="ui-icon ui-icon-heart accountLinkListEntry"></span><a href='<c:url value="/accountNotifications"/>'>View or change my product notification list.</a></li>
    </ul>
  </div>
</div>

src/main/webapp/WEB-INF/jsp/checkoutPayment.jsp
<%@ include file="/WEB-INF/layout/taglibs.jsp"%>
<script type="text/javascript"><!--
var selected;

function selectRowEffect(object, buttonSelect) {
  if (!selected) {
    if (document.getElementById) {
      selected = document.getElementById('defaultSelected');
    } else {
      selected = document.all['defaultSelected'];
    }
  }

  if (selected) selected.className = 'moduleRow';
  object.className = 'moduleRowSelected';
  selected = object;

// one button is not an array
  if (document.checkout_payment.payment[0]) {
    document.checkout_payment.payment[buttonSelect].checked=true;
  } else {
    document.checkout_payment.payment.checked=true;
  }
}

function rowOverEffect(object) {
  if (object.className == 'moduleRow') object.className = 'moduleRowOver';
}

function rowOutEffect(object) {
  if (object.className == 'moduleRowOver') object.className = 'moduleRow';
}
//--></script>
<script type="text/javascript"><!-- 
function check_form() {
  var error = 0;
  var error_message = "Errors have occured during the process of your form.\n\nPlease make the following corrections:\n\n";
  var payment_value = null;
  if (document.checkout_payment.payment.length) {
    for (var i=0; i<document.checkout_payment.payment.length; i++) {
      if (document.checkout_payment.payment[i].checked) {
        payment_value = document.checkout_payment.payment[i].value;
      }
    }
  } else if (document.checkout_payment.payment.checked) {
    payment_value = document.checkout_payment.payment.value;
  } else if (document.checkout_payment.payment.value) {
    payment_value = document.checkout_payment.payment.value;
  }


  if (payment_value == null) {
    error_message = error_message + "* Please select a payment method for your order.\n";
    error = 1;
  }

  if (error == 1) {
    alert(error_message);
    return false;
  } else {
    return true;
  }
}
//--></script>

<h1>Payment Information</h1>

<form name="checkout_payment" action="<c:url value="/checkout/confirmation" />" method="get" onsubmit="return check_form();"><input type="hidden" name="formid" value="ba9cd75f52b4b6bd3f9bdc27060bbb7e" />
<div class="contentContainer">


  <h2>Billing Address</h2>

  <div class="contentText">
    <div class="ui-widget infoBoxContainer" style="float: right;">
      <div class="ui-widget-header infoBoxHeading">Billing Address:</div>

      <div class="ui-widget-content infoBoxContents">
        ${checkout.paymentAddress.formattedAddress}      </div>
    </div>

    Please choose from your address book where you would like the invoice to be sent to.<br /><br /><span class="tdbLink"><a id="tdb5" href="<c:url value="/checkout/paymentAddress" />">Change Address</a></span><script type="text/javascript">$("#tdb5").button({icons:{primary:"ui-icon-home"}}).addClass("ui-priority-secondary").parent().removeClass("tdbLink");</script>  </div>

  <div style="clear: both;"></div>

  <h2>Payment Method</h2>


  <div class="contentText">
    <div style="float: right;">
      <strong>Please Select</strong>    </div>

    Please select the preferred payment method to use on this order.  </div>


  <div class="contentText">


    <table border="0" width="100%" cellspacing="0" cellpadding="2">

      <tr id="defaultSelected" class="moduleRowSelected" onmouseover="rowOverEffect(this)" onmouseout="rowOutEffect(this)" onclick="selectRowEffect(this, 0)">

        <td><strong>Cash on Delivery</strong></td>
        <td align="right">

<input type="radio" name="payment" value="cod" checked="checked" />
        </td>
      </tr>


    </table>


    <table border="0" width="100%" cellspacing="0" cellpadding="2">

      <tr class="moduleRow" onmouseover="rowOverEffect(this)" onmouseout="rowOutEffect(this)" onclick="selectRowEffect(this, 1)">

        <td><strong>PayPal (including Credit and Debit Cards)</strong></td>
        <td align="right">

<input type="radio" name="payment" value="paypal_express" />
        </td>
      </tr>


    </table>


  </div>

  <h2>Add Comments About Your Order</h2>

  <div class="contentText">
    <textarea name="comments" cols="60" rows="5"></textarea>  </div>

  <div class="contentText">
    <div style="float: left; width: 60%; padding-top: 5px; padding-left: 15%;">
      <div id="coProgressBar" style="height: 5px;"></div>

      <table border="0" width="100%" cellspacing="0" cellpadding="2">
        <tr>
          <td align="center" width="33%" class="checkoutBarFrom"><a href="http://34.232.222.96/oscommerce2/catalog/checkout_shipping.php" class="checkoutBarFrom">Delivery Information</a></td>
          <td align="center" width="33%" class="checkoutBarCurrent">Payment Information</td>
          <td align="center" width="33%" class="checkoutBarTo">Confirmation</td>
        </tr>
      </table>
    </div>

    <div style="float: right;"><span class="tdbLink"><button id="tdb6" type="submit">Continue</button></span><script type="text/javascript">$("#tdb6").button({icons:{primary:"ui-icon-triangle-1-e"}}).addClass("ui-priority-primary").parent().removeClass("tdbLink");</script></div>
  </div>
</div>

<script type="text/javascript">
$('#coProgressBar').progressbar({
  value: 66
});
</script>

</form>

src/main/webapp/WEB-INF/jsp/checkoutShipping.jsp
<%@ include file="/WEB-INF/layout/taglibs.jsp"%>

<script type="text/javascript"><!--
var selected;

function selectRowEffect(object, buttonSelect) {
  if (!selected) {
    if (document.getElementById) {
      selected = document.getElementById('defaultSelected');
    } else {
      selected = document.all['defaultSelected'];
    }
  }

  if (selected) selected.className = 'moduleRow';
  object.className = 'moduleRowSelected';
  selected = object;

// one button is not an array
  if (document.checkout_address.shipping[0]) {
    document.checkout_address.shipping[buttonSelect].checked=true;
  } else {
    document.checkout_address.shipping.checked=true;
  }
}

function rowOverEffect(object) {
  if (object.className == 'moduleRow') object.className = 'moduleRowOver';
}

function rowOutEffect(object) {
  if (object.className == 'moduleRowOver') object.className = 'moduleRow';
}
//--></script>

<h1>Delivery Information</h1>

<form name="checkout_address" action="<c:url value="/checkout/payment" />" method="get"><input type="hidden" name="formid" value="ba9cd75f52b4b6bd3f9bdc27060bbb7e" /><input type="hidden" name="action" value="process" />
<div class="contentContainer">
  <h2>Shipping Address</h2>

  <div class="contentText">
    <div class="ui-widget infoBoxContainer" style="float: right;">
      <div class="ui-widget-header infoBoxHeading">Shipping Address:</div>

      <div class="ui-widget-content infoBoxContents">
      ${checkout.shippingAddress.formattedAddress}      </div>
    </div>

    Please choose from your address book where you would like the items to be delivered to.<br /><br /><span class="tdbLink"><a id="tdb5" href="<c:url value="/checkout/shippingAddress" />">Change Address</a></span><script type="text/javascript">$("#tdb5").button({icons:{primary:"ui-icon-home"}}).addClass("ui-priority-secondary").parent().removeClass("tdbLink");</script>  </div>

  <div style="clear: both;"></div>


  <h2>Shipping Method</h2>


  <div class="contentText">
    This is currently the only shipping method available to use on this order.  </div>


  <div class="contentText">
    <table border="0" width="100%" cellspacing="0" cellpadding="2">


      <tr>
        <td colspan="3"><strong>Flat Rate</strong>&nbsp;</td>
      </tr>

      <tr id="defaultSelected" class="moduleRowSelected" onmouseover="rowOverEffect(this)" onmouseout="rowOutEffect(this)" onclick="selectRowEffect(this, 0)">

        <td width="75%" style="padding-left: 15px;">Best Way</td>


        <td align="right" colspan="2">$5.00<input type="hidden" name="shipping" value="flat_flat" /></td>


      </tr>


    </table>
  </div>


  <h2>Add Comments About Your Order</h2>

  <div class="contentText">
    <textarea name="comments" cols="60" rows="5"></textarea>  </div>

  <div class="contentText">
    <div style="float: left; width: 60%; padding-top: 5px; padding-left: 15%;">
      <div id="coProgressBar" style="height: 5px;"></div>

      <table border="0" width="100%" cellspacing="0" cellpadding="2">
        <tr>
          <td align="center" width="33%" class="checkoutBarCurrent">Delivery Information</td>
          <td align="center" width="33%" class="checkoutBarTo">Payment Information</td>
          <td align="center" width="33%" class="checkoutBarTo">Confirmation</td>
        </tr>
      </table>
    </div>

    <div style="float: right;"><span class="tdbLink"><button id="tdb6" type="submit">Continue</button></span><script type="text/javascript">$("#tdb6").button({icons:{primary:"ui-icon-triangle-1-e"}}).addClass("ui-priority-primary").parent().removeClass("tdbLink");</script></div>
  </div>
</div>

<script type="text/javascript">
$('#coProgressBar').progressbar({
  value: 33
});
</script>

</form>